export const studentEvaluationQuestions = [
    { code: 'STU_Q1', text: 'Gives course outline and references at beginning', type: 'rating' },
    { code: 'STU_Q2', text: 'Offers lab/practical sessions when applicable', type: 'rating' },
    { code: 'STU_Q3', text: 'Punctual for class', type: 'rating' },
    { code: 'STU_Q4', text: 'Well prepared and organized', type: 'rating' },
    { code: 'STU_Q5', text: 'Strong subject matter knowledge', type: 'rating' },
    { code: 'STU_Q6', text: 'Clear delivery of topics', type: 'rating' },
    { code: 'STU_Q7', text: 'Encourages participation and questions', type: 'rating' },
    { code: 'STU_Q8', text: 'Fully covers course outline', type: 'rating' },
    { code: 'STU_Q9', text: 'Relates topics to real-world', type: 'rating' },
    { code: 'STU_Q10', text: 'Informs grading criteria early', type: 'rating' },
    { code: 'STU_Q11', text: 'Creates interest in the subject', type: 'rating' },
    { code: 'STU_Q12', text: 'Returns assessments on time', type: 'rating' },
    { code: 'STU_Q13', text: 'Writes key points clearly', type: 'rating' },
    { code: 'STU_Q14', text: 'Uses relevant instructional aids', type: 'rating' },
    { code: 'STU_Q15', text: 'Uses continuous assessment', type: 'rating' },
    { code: 'STU_Q16', text: 'Available for consultation', type: 'rating' },
    { code: 'STU_Q17', text: 'Considers differences among learners', type: 'rating' },
    { code: 'STU_Q18', text: 'Exams reflect topics covered', type: 'rating' },
    { code: 'STU_Q19', text: 'Demonstrates discipline and professionalism', type: 'rating' },
    { code: 'STU_S1', text: 'Strengths', type: 'text' },
    { code: 'STU_S2', text: 'Areas for improvement', type: 'text' },
];

export const peerEvaluationQuestions = [
    { code: 'PEER_Q1', text: 'Prepares and updates teaching materials', type: 'rating' },
    { code: 'PEER_Q2', text: 'Updates subject matter continuously', type: 'rating' },
    { code: 'PEER_Q3', text: 'Demonstrates subject expertise', type: 'rating' },
    { code: 'PEER_Q4', text: 'Engages in research & community services', type: 'rating' },
    { code: 'PEER_Q5', text: 'Participates in seminars/workshops', type: 'rating' },
    { code: 'PEER_Q6', text: 'Collaborates with colleagues', type: 'rating' },
    { code: 'PEER_Q7', text: 'Teamwork attitude', type: 'rating' },
    { code: 'PEER_Q8', text: 'Advising and supporting students', type: 'rating' },
    { code: 'PEER_Q9', text: 'Contributes to improving teaching-learning', type: 'rating' },
    { code: 'PEER_Q10', text: 'Preparedness for new teaching methods', type: 'rating' },
    { code: 'PEER_Q11', text: 'Ethical & respectful behavior', type: 'rating' },
    { code: 'PEER_Q12', text: 'Follows institutional regulations', type: 'rating' },
    { code: 'PEER_Q13', text: 'Demonstrates professionalism', type: 'rating' },
    { code: 'PEER_Q14', text: 'Time management & consultation hours', type: 'rating' },
    { code: 'PEER_S1', text: 'Strengths', type: 'text' },
    { code: 'PEER_S2', text: 'Areas for improvement', type: 'text' },
];

export const departmentHeadEvaluationQuestions = [
    { code: 'DEPT_Q1', text: 'Course plan quality', type: 'rating' },
    { code: 'DEPT_Q2', text: 'Assessment strategy compliance', type: 'rating' },
    { code: 'DEPT_Q3', text: 'Documentation submission', type: 'rating' },
    { code: 'DEPT_Q4', text: 'Collaboration with department', type: 'rating' },
    { code: 'DEPT_Q5', text: 'Professional behavior', type: 'rating' },
    { code: 'DEPT_Q6', text: 'Punctuality & scheduling', type: 'rating' },
    { code: 'DEPT_Q7', text: 'Contribution to curriculum development', type: 'rating' },
    { code: 'DEPT_Q8', text: 'Supports institutional goals', type: 'rating' },
    { code: 'DEPT_Q9', text: 'Participation in committees', type: 'rating' },
    { code: 'DEPT_Q10', text: 'Communication with staff', type: 'rating' },
    { code: 'DEPT_S1', text: 'Strengths', type: 'text' },
    { code: 'DEPT_S2', text: 'Improvement Needed', type: 'text' },
];
